"use client";

import { useState } from "react";
import { ArrowRight, CheckCircle2, Mail, Smartphone } from "lucide-react";

export default function PatientPortal() {
  const [sent, setSent] = useState(false);
  return <main className="min-h-screen bg-[#f6f8f7] px-5 pb-24 pt-10 text-slate-950 sm:px-10"><div className="mx-auto max-w-lg"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-2xl bg-teal-700 font-black text-white">M</span><span className="font-semibold">MediCore Patient Portal</span></div><div className="mt-16"><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-700">Your care, connected</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">Sign in without a password.</h1><p className="mt-4 leading-7 text-slate-600">We&apos;ll send a secure one-time code or magic link to your phone or email.</p>{sent ? <div className="mt-10 rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><CheckCircle2 className="size-6 text-emerald-600" /><p className="mt-3 font-semibold text-emerald-950">Check your messages</p><p className="mt-1 text-sm text-emerald-800">Your secure sign-in link is on its way.</p></div> : <form onSubmit={(event) => { event.preventDefault(); setSent(true); }} className="mt-10 space-y-4"><label className="block text-sm font-semibold">Mobile number or email<input required type="text" placeholder="you@example.com" className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-4 outline-none ring-teal-500 focus:ring-2" /></label><button className="w-full rounded-xl bg-slate-950 px-4 py-4 font-semibold text-white hover:bg-slate-800">Send secure link <ArrowRight className="ml-2 inline size-4" /></button><div className="grid grid-cols-2 gap-3 pt-2"><button type="button" className="rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm font-semibold"><Smartphone className="mr-2 inline size-4 text-teal-700" />Use OTP</button><button type="button" className="rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm font-semibold"><Mail className="mr-2 inline size-4 text-teal-700" />Magic link</button></div></form>}</div></div><nav className="fixed inset-x-0 bottom-0 border-t border-slate-200 bg-white/95 px-6 py-3 backdrop-blur"><div className="mx-auto flex max-w-lg justify-around text-xs font-semibold text-teal-700"><span>Home</span><span>Appointments</span><span>Messages</span><span>Profile</span></div></nav></main>;
}
