server:
  port: 8085

spring:
  application:
    name: appointment-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:7777}/${APPOINTMENT_DB_NAME:heal_appointment}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:shvetpass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 5000ms
        failure-rate-threshold: 50
        slow-call-rate-threshold: 70
        slow-call-duration-threshold: 2000ms
        register-health-indicator: true
    instances:
      patient-service:
        base-config: default
      doctor-service:
        base-config: default
      patientService:
        base-config: default
      doctorService:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 3s
        cancel-running-future: true
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 500ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
