-- V1: Core Clinical Schema
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Encounters Table
CREATE TABLE IF NOT EXISTS encounters (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    patient_id UUID NOT NULL,
    doctor_id UUID NOT NULL,
    nurse_id UUID,
    department_id UUID,
    type VARCHAR(32) NOT NULL, -- INPATIENT, OUTPATIENT, EMERGENCY, ICU, SURGERY
    status VARCHAR(32) NOT NULL DEFAULT 'PLANNED', -- PLANNED, IN_PROGRESS, COMPLETED, DISCHARGED, CANCELLED
    start_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP WITH TIME ZONE,
    chief_complaint TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2. Clinical Entries Table (Immutable, Append-Only)
CREATE TABLE IF NOT EXISTS clinical_entries (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    encounter_id UUID NOT NULL REFERENCES encounters(id) ON DELETE RESTRICT,
    patient_id UUID NOT NULL,
    author_id UUID NOT NULL,
    author_name VARCHAR(128) NOT NULL,
    author_role VARCHAR(32) NOT NULL, -- DOCTOR, NURSE
    entry_type VARCHAR(64) NOT NULL, -- SOAP_NOTE, DIAGNOSIS, PRESCRIPTION, LAB_ORDER, RADIOLOGY_ORDER, PROCEDURE_NOTE, DISCHARGE_SUMMARY, VITALS_SIGN, NURSE_NOTE, MEDICATION_ADMINISTRATION, INTAKE_OUTPUT, WOUND_CARE, SHIFT_HANDOFF
    content_json JSONB NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT', -- DRAFT, SIGNED, AMENDED, CANCELLED
    is_correction BOOLEAN NOT NULL DEFAULT FALSE,
    original_entry_id UUID REFERENCES clinical_entries(id) ON DELETE RESTRICT,
    correction_reason TEXT,
    signed_at TIMESTAMP WITH TIME ZONE,
    signed_by_id UUID,
    signed_by_name VARCHAR(128),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3. Nurse Flags Table
CREATE TABLE IF NOT EXISTS nurse_flags (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    encounter_id UUID NOT NULL REFERENCES encounters(id) ON DELETE RESTRICT,
    patient_id UUID NOT NULL,
    nurse_id UUID NOT NULL,
    nurse_name VARCHAR(128) NOT NULL,
    flag_type VARCHAR(64) NOT NULL, -- ABNORMAL_VITALS, CRITICAL_LAB_VALUE, PATIENT_DETERIORATION, ALLERGY_CONFLICT, MEDICATION_CONCERN, FALL_RISK, OTHER
    severity VARCHAR(32) NOT NULL, -- LOW, MEDIUM, HIGH, CRITICAL
    message TEXT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'OPEN', -- OPEN, ACKNOWLEDGED, RESOLVED, DISMISSED
    response_entry_id UUID REFERENCES clinical_entries(id) ON DELETE SET NULL,
    acknowledged_by UUID,
    acknowledged_at TIMESTAMP WITH TIME ZONE,
    resolved_by UUID,
    resolved_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
